from __future__ import annotations

import argparse
import json
import os
import sys
import time
import urllib.error
import urllib.request
from pathlib import Path
from typing import Any

import yaml


def load_yaml(path: Path) -> dict[str, Any]:
    if not path.exists():
        raise SystemExit(f"MISSING_CONFIG: {path}")
    data = yaml.safe_load(path.read_text(encoding="utf-8"))
    if not isinstance(data, dict):
        raise SystemExit(f"INVALID_CONFIG: {path}")
    return data


def deep_get(data: dict[str, Any], dotted: str, default: Any = None) -> Any:
    cur: Any = data
    for part in dotted.split("."):
        if not isinstance(cur, dict) or part not in cur:
            return default
        cur = cur[part]
    return cur


def ensure_dir(path: Path, execute: bool) -> None:
    if execute:
        path.mkdir(parents=True, exist_ok=True)
    print(f"{'ENSURED' if execute else 'WOULD_CREATE'} {path}")


def post_json(url: str, payload: dict[str, Any], timeout: int) -> dict[str, Any]:
    data = json.dumps(payload).encode("utf-8")
    req = urllib.request.Request(
        url,
        data=data,
        headers={"Content-Type": "application/json"},
        method="POST",
    )
    with urllib.request.urlopen(req, timeout=timeout) as resp:
        raw = resp.read().decode("utf-8", errors="replace")
    if not raw.strip():
        return {}
    try:
        return json.loads(raw)
    except json.JSONDecodeError:
        return {"raw": raw}


def get_json(url: str, timeout: int) -> dict[str, Any]:
    with urllib.request.urlopen(url, timeout=timeout) as resp:
        raw = resp.read().decode("utf-8", errors="replace")
    return json.loads(raw) if raw.strip() else {}


def normalize_endpoint(endpoint: str) -> str:
    return endpoint.rstrip("/")


def ollama_tags(endpoint: str) -> dict[str, Any]:
    return get_json(normalize_endpoint(endpoint) + "/api/tags", timeout=15)


def ollama_pull(endpoint: str, model: str, execute: bool) -> None:
    endpoint = normalize_endpoint(endpoint)
    print(f"OLLAMA_MODEL={model}")
    print(f"OLLAMA_ENDPOINT={endpoint}")
    print(f"OLLAMA_PULL_URL={endpoint}/api/pull")

    if not execute:
        print("DRY_RUN: would call Ollama /api/pull. No model download performed.")
        return

    try:
        tags_before = ollama_tags(endpoint)
        print("OLLAMA_REACHABLE_BEFORE_PULL=1")
        print("OLLAMA_TAGS_BEFORE:", json.dumps(tags_before, ensure_ascii=False)[:2000])
    except Exception as exc:
        raise SystemExit(f"OLLAMA_NOT_REACHABLE: {endpoint} error={exc}") from exc

    started = time.time()
    result = post_json(endpoint + "/api/pull", {"model": model, "stream": False}, timeout=60 * 60 * 6)
    elapsed = time.time() - started

    print("OLLAMA_PULL_DONE")
    print(f"elapsed_sec={elapsed:.1f}")
    print("result:", json.dumps(result, ensure_ascii=False)[:4000])


def hf_snapshot_download(model_id: str, cache_dir: Path, execute: bool, allow_patterns: list[str], ignore_patterns: list[str]) -> None:
    print(f"HF_MODEL={model_id}")
    print(f"HF_HUB_CACHE={cache_dir}")

    if not execute:
        print("DRY_RUN: would call huggingface_hub.snapshot_download. No model download performed.")
        return

    try:
        from huggingface_hub import snapshot_download
    except Exception as exc:
        raise SystemExit(
            "MISSING_PYTHON_PACKAGE: huggingface_hub. "
            "Install it on the server image/environment before HF model download."
        ) from exc

    local_dir = snapshot_download(
        repo_id=model_id,
        cache_dir=str(cache_dir),
        allow_patterns=allow_patterns or None,
        ignore_patterns=ignore_patterns or None,
        local_files_only=False,
    )
    print("HF_SNAPSHOT_DOWNLOAD_DONE")
    print(f"local_dir={local_dir}")


def write_runtime_env(cfg: dict[str, Any], output: Path, project_root: Path, execute: bool) -> None:
    mc = cfg.get("model_cache", {}) if isinstance(cfg.get("model_cache", {}), dict) else {}

    root_dir = project_root / str(mc.get("root_dir", "model_cache"))
    ollama_dir = project_root / str(mc.get("ollama_models_dir", "model_cache/ollama"))
    hf_home = project_root / str(mc.get("hf_home", "model_cache/huggingface"))
    hf_hub_cache = project_root / str(mc.get("hf_hub_cache", "model_cache/huggingface/hub"))
    transformers_cache = project_root / str(mc.get("transformers_cache", "model_cache/huggingface/transformers"))

    lines = [
        "# Generated by scripts/server_prepare_model_cache.py",
        "# Source this on the server before starting local model services.",
        f"MODEL_CACHE_ROOT={root_dir.as_posix()}",
        f"OLLAMA_MODELS={ollama_dir.as_posix()}",
        f"HF_HOME={hf_home.as_posix()}",
        f"HF_HUB_CACHE={hf_hub_cache.as_posix()}",
        f"TRANSFORMERS_CACHE={transformers_cache.as_posix()}",
        f"OLLAMA_ENDPOINT={deep_get(cfg, 'model_cache.ollama.host_endpoint_for_server', 'http://127.0.0.1:11434')}",
        f"QWEN_VLM_OLLAMA_MODEL={deep_get(cfg, 'model_cache.qwen_vlm.ollama_model', 'qwen3-vl:8b-thinking')}",
        f"QWEN_VLM_HF_MODEL={deep_get(cfg, 'model_cache.qwen_vlm.hf_model', 'Qwen/Qwen3-VL-8B-Thinking')}",
        "",
    ]

    if execute:
        output.parent.mkdir(parents=True, exist_ok=True)
        output.write_text("\n".join(lines), encoding="utf-8")
        print(f"WROTE_RUNTIME_ENV={output}")
    else:
        print(f"DRY_RUN: would write runtime env to {output}")
        print("\n".join(lines))


def main() -> int:
    parser = argparse.ArgumentParser(
        description="Prepare persistent server model cache for local VLM/3DGS without downloading unless --execute is passed."
    )
    parser.add_argument("--config", default="configs/site01.yaml")
    parser.add_argument("--provider", choices=["ollama", "hf", "both", "env_only"], default="env_only")
    parser.add_argument("--execute", action="store_true", help="Actually create dirs and download/pull models.")
    parser.add_argument("--project-root", default=".")
    parser.add_argument("--runtime-env-out", default="model_cache/server_model_env.sh")
    parser.add_argument("--ollama-endpoint", default=None)
    parser.add_argument("--ollama-model", default=None)
    parser.add_argument("--hf-model", default=None)
    args = parser.parse_args()

    project_root = Path(args.project_root).resolve()
    cfg = load_yaml(project_root / args.config)

    mc = cfg.get("model_cache", {}) if isinstance(cfg.get("model_cache", {}), dict) else {}

    root_dir = project_root / str(mc.get("root_dir", "model_cache"))
    ollama_dir = project_root / str(mc.get("ollama_models_dir", "model_cache/ollama"))
    hf_home = project_root / str(mc.get("hf_home", "model_cache/huggingface"))
    hf_hub_cache = project_root / str(mc.get("hf_hub_cache", "model_cache/huggingface/hub"))
    transformers_cache = project_root / str(mc.get("transformers_cache", "model_cache/huggingface/transformers"))

    ollama_model = args.ollama_model or deep_get(cfg, "model_cache.qwen_vlm.ollama_model", "qwen3-vl:8b-thinking")
    hf_model = args.hf_model or deep_get(cfg, "model_cache.qwen_vlm.hf_model", "Qwen/Qwen3-VL-8B-Thinking")
    ollama_endpoint = args.ollama_endpoint or deep_get(
        cfg,
        "model_cache.ollama.host_endpoint_for_server",
        deep_get(cfg, "copilot.vlm.endpoint", "http://127.0.0.1:11434"),
    )

    allow_patterns = deep_get(cfg, "model_cache.huggingface.allow_patterns", []) or []
    ignore_patterns = deep_get(cfg, "model_cache.huggingface.ignore_patterns", []) or []

    print("SERVER_MODEL_CACHE_PREPARE")
    print(f"execute={args.execute}")
    print(f"provider={args.provider}")
    print(f"project_root={project_root}")

    for path in [root_dir, ollama_dir, hf_home, hf_hub_cache, transformers_cache]:
        ensure_dir(path, args.execute)

    os.environ.setdefault("OLLAMA_MODELS", str(ollama_dir))
    os.environ.setdefault("HF_HOME", str(hf_home))
    os.environ.setdefault("HF_HUB_CACHE", str(hf_hub_cache))
    os.environ.setdefault("TRANSFORMERS_CACHE", str(transformers_cache))

    write_runtime_env(cfg, project_root / args.runtime_env_out, project_root, args.execute)

    if args.provider in {"ollama", "both"}:
        ollama_pull(ollama_endpoint, ollama_model, args.execute)

    if args.provider in {"hf", "both"}:
        hf_snapshot_download(hf_model, hf_hub_cache, args.execute, allow_patterns, ignore_patterns)

    print("SERVER_MODEL_CACHE_PREPARE_DONE")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
