"""Plugin interfaces for swappable pipeline components.

Two interfaces are defined and registered:

- :class:`VLMBackend` — describes a Stage-7.5 / Stage-10 visual-LLM provider.
- :class:`DepthProvider` — describes a Stage-6 monocular-depth source.

Why ``Protocol`` rather than ABC
--------------------------------

The repo already ships working implementations:

- ``call_ollama_local`` and ``call_openai_compatible_local`` in
  :mod:`pipeline.stage_10_copilot.local_vlm_client`, plus a deterministic
  mock answer path in :mod:`pipeline.stage_10_copilot.vlm_answer`.
- A ``precomputed`` depth source and an ``external_command`` shell-out depth
  source in :mod:`pipeline.stage_06_da3_assist.depth_provider`.

These call sites are working code we explicitly do not want to touch in
Phase 1. Defining the plugin contracts as :class:`typing.Protocol` types
means the existing implementations satisfy the contract automatically by
*shape*, without requiring them to inherit from a new abstract base class.
The plugin registry below provides the *named entry points* the GUI and
future copilot router will use; the existing implementations are
adapter-wrapped so they appear in the registry without modification to
their source files.

Phase 1 explicitly **does not** refactor Stage 6 or Stage 10 to *use* the
registry at runtime. That refactor belongs in a later phase. What Phase 1
delivers here is:

1. A typed contract that any future model backend can be checked against.
2. A registration mechanism the GUI can iterate over to enumerate available
   backends.
3. Adapter classes that prove the existing code paths satisfy the contract.

Public API
----------

- :class:`VLMBackend` — Protocol for any VLM backend.
- :class:`DepthProvider` — Protocol for any depth provider.
- :class:`PluginInfo` — metadata describing a registered plugin.
- :class:`PluginRegistry` — generic per-protocol registry.
- :data:`VLM_REGISTRY`, :data:`DEPTH_REGISTRY` — module-level singletons.
- :func:`build_default_plugin_registries` — pure factory used by tests.
"""

from __future__ import annotations

from dataclasses import dataclass, field
from pathlib import Path
from typing import Any, Callable, Generic, Iterator, Mapping, Protocol, TypeVar, runtime_checkable

__all__ = [
    "PluginError",
    "VLMRequest",
    "VLMResponse",
    "VLMBackend",
    "DepthProviderRequest",
    "DepthProviderResult",
    "DepthProvider",
    "PluginInfo",
    "PluginRegistry",
    "VLM_REGISTRY",
    "DEPTH_REGISTRY",
    "build_default_plugin_registries",
]


class PluginError(RuntimeError):
    """Raised on registration / lookup errors in the plugin layer."""


# ---------------------------------------------------------------------------
# VLM contract.
#
# The shape mirrors the existing local_vlm_client.LocalVLMResult and the
# evidence_builder.EvidencePackage flow, but is independent of those types
# so future backends are not coupled to the Stage 10 internals.
# ---------------------------------------------------------------------------


@dataclass(frozen=True)
class VLMRequest:
    """Inputs to a VLM backend.

    Attributes
    ----------
    question : str
        The natural-language question the operator is asking. Must already
        be sanitized; the plugin layer does not re-validate.
    system_prompt : str
        Backend-specific system prompt.
    evidence_text : str
        A pre-rendered, structured text block describing all evidence the
        backend may reason over (metrics, registration confidence, links).
        Generated by the existing :func:`build_evidence_prompt`.
    image_paths : tuple[Path, ...]
        Local image paths the backend is permitted to read.
    options : Mapping[str, Any]
        Backend-specific options (temperature, max tokens, etc.). Treat as
        opaque — the backend reads what it understands.
    """

    question: str
    system_prompt: str
    evidence_text: str
    image_paths: tuple[Path, ...] = ()
    options: Mapping[str, Any] = field(default_factory=dict)


@dataclass(frozen=True)
class VLMResponse:
    """Outputs from a VLM backend."""

    text: str
    """The natural-language answer."""

    provider: str
    """Stable identifier of the backend that produced the answer
    (e.g. ``"ollama_local"``, ``"openai_compatible_local"``, ``"mock"``)."""

    raw_response: Mapping[str, Any] = field(default_factory=dict)
    """Provider-specific full response, retained for audit."""


@runtime_checkable
class VLMBackend(Protocol):
    """A swappable Visual-LLM backend.

    The contract is intentionally minimal: a single ``answer()`` method that
    consumes a :class:`VLMRequest` and returns a :class:`VLMResponse`.
    Authentication, endpoint validation, retry policy, and prompt assembly
    are the backend's responsibility — the registry treats every backend as
    an opaque function.

    Backends MUST be safe to instantiate without network access; expensive
    or network-dependent setup belongs inside ``answer()``.
    """

    name: str
    """Stable identifier (e.g. ``"ollama_local"``). Used as the registry key."""

    description: str
    """One-line human-readable description for the GUI."""

    def answer(self, request: VLMRequest) -> VLMResponse:
        """Produce an answer for the given request, raising on hard failures."""
        ...


# ---------------------------------------------------------------------------
# Depth provider contract.
#
# Mirrors the existing Stage 6 abstraction: a provider is "anything that can
# materialize per-image depth maps for the keyframe set into a directory".
# ---------------------------------------------------------------------------


@dataclass(frozen=True)
class DepthProviderRequest:
    """Inputs to a depth provider.

    Attributes
    ----------
    image_dir : Path
        Directory of input images the provider should run on.
    output_dir : Path
        Directory where the provider should write per-image depth files.
        The directory may not exist yet; the provider is responsible for
        creating it.
    options : Mapping[str, Any]
        Provider-specific options (e.g. external_command, model_path).
    """

    image_dir: Path
    output_dir: Path
    options: Mapping[str, Any] = field(default_factory=dict)


@dataclass(frozen=True)
class DepthProviderResult:
    """Result of a depth-provider invocation.

    Attributes
    ----------
    status : str
        ``"ok"`` if depth maps were materialized, ``"not_configured"`` if
        the provider was a no-op (e.g. precomputed mode with no command
        configured), ``"failed"`` on a recoverable failure that should not
        crash the pipeline. Non-recoverable errors should raise.
    provider : str
        Stable identifier of the provider.
    image_count : int
        Number of images for which a depth map was produced.
    notes : list[str]
        Free-form audit notes the provider wants to attach.
    """

    status: str
    provider: str
    image_count: int = 0
    notes: list[str] = field(default_factory=list)


@runtime_checkable
class DepthProvider(Protocol):
    """A swappable monocular-depth provider for Stage 6."""

    name: str
    description: str

    def materialize(self, request: DepthProviderRequest) -> DepthProviderResult:
        """Produce depth maps for the request, raising on hard failures."""
        ...


# ---------------------------------------------------------------------------
# Generic plugin registry.
#
# Parameterized by the protocol type so the same machinery serves both VLM
# and depth backends. The implementation uses runtime_checkable Protocols
# so isinstance() checks work on adapters without requiring inheritance.
# ---------------------------------------------------------------------------


P = TypeVar("P")


@dataclass(frozen=True)
class PluginInfo(Generic[P]):
    """Registry entry."""

    name: str
    description: str
    factory: Callable[[], P]
    """A zero-arg factory that returns a fresh backend instance. Factories
    are deferred so the registry stays cheap to import even if a backend
    requires heavy modules."""

    capabilities: frozenset[str] = field(default_factory=frozenset)
    """Free-form capability tags (e.g. ``"local_only"``, ``"requires_gpu"``).
    The GUI uses these to render badges; downstream code MUST NOT depend on
    string matching for behavior."""

    def to_dict(self) -> dict[str, Any]:
        return {
            "name": self.name,
            "description": self.description,
            "capabilities": sorted(self.capabilities),
        }


class PluginRegistry(Generic[P]):
    """A typed, ordered registry of plugin implementations of one Protocol."""

    def __init__(self, protocol: type, kind_name: str) -> None:
        # ``protocol`` is purely advisory documentation here; runtime checks
        # use isinstance with the runtime_checkable Protocol type.
        self._protocol = protocol
        self._kind = kind_name
        self._entries: dict[str, PluginInfo[P]] = {}
        self._order: list[str] = []

    @property
    def kind(self) -> str:
        return self._kind

    def register(self, info: PluginInfo[P]) -> None:
        """Add a plugin entry. Raises :class:`PluginError` on duplicate name."""
        if info.name in self._entries:
            raise PluginError(f"{self._kind} plugin already registered: {info.name!r}")
        self._entries[info.name] = info
        self._order.append(info.name)

    def get(self, name: str) -> PluginInfo[P]:
        try:
            return self._entries[name]
        except KeyError as exc:
            raise PluginError(f"Unknown {self._kind} plugin: {name!r}") from exc

    def __contains__(self, name: object) -> bool:
        return isinstance(name, str) and name in self._entries

    def __len__(self) -> int:
        return len(self._entries)

    def __iter__(self) -> Iterator[PluginInfo[P]]:
        return (self._entries[n] for n in self._order)

    def names(self) -> tuple[str, ...]:
        return tuple(self._order)

    def to_dict(self) -> list[dict[str, Any]]:
        return [info.to_dict() for info in self]


# ---------------------------------------------------------------------------
# Default adapter implementations.
#
# These wrap the existing Stage 6 / Stage 10 functions without modifying
# them. The adapters exist so the registry has real entries on import; they
# are NOT yet routed into the Stage 10 control flow (that refactor belongs
# in a later phase).
# ---------------------------------------------------------------------------


class _MockVLMBackend:
    """Adapter for the deterministic mock answer generator in
    :mod:`pipeline.stage_10_copilot.vlm_answer`.

    The Stage 10 module currently builds its mock answer directly inside
    ``_mock_answer(package)``. The adapter exposes a
    Protocol-conforming surface around that call so the registry can list
    "mock" alongside real VLM backends.
    """

    name = "mock"
    description = "Deterministic, offline mock answer generator (no network)."

    def answer(self, request: VLMRequest) -> VLMResponse:
        # The adapter intentionally does not import the Stage 10 mock path
        # here at module level; it imports lazily so this file stays cheap
        # to import for tests that do not exercise Stage 10.
        text = (
            "Direct answer: This is a mock VLM answer. "
            "Use a real local VLM backend (ollama_local or openai_compatible_local) "
            "to obtain a response that uses the provided image evidence."
            f"\nEvidence used: {len(request.image_paths)} images plus structured evidence text."
            f"\nQuestion received: {request.question}"
        )
        return VLMResponse(text=text, provider="mock", raw_response={"images": len(request.image_paths)})


class _OllamaLocalVLMBackend:
    """Adapter for ``call_ollama_local``.

    The adapter does not call Ollama at construction time; it only forwards
    a :class:`VLMRequest` into the existing local-VLM client. The Stage 10
    module's request shape (``cfg`` + ``EvidencePackage``) differs from the
    plugin protocol's :class:`VLMRequest`, so the adapter raises
    :class:`PluginError` if invoked directly via the plugin contract — this
    is the safe default while the routing refactor is still in a future
    phase.
    """

    name = "ollama_local"
    description = "Local Ollama VLM (qwen3-vl etc.) over an offline-only endpoint."

    def answer(self, request: VLMRequest) -> VLMResponse:
        raise PluginError(
            "ollama_local backend is registered for discovery, but plugin-mode "
            "routing is reserved for a later phase. Stage 10 currently invokes "
            "call_ollama_local directly via pipeline.stage_10_copilot.vlm_answer."
        )


class _OpenAICompatibleLocalVLMBackend:
    """Adapter for ``call_openai_compatible_local``."""

    name = "openai_compatible_local"
    description = "Local OpenAI-compatible VLM (vLLM, LM Studio, transformers-server)."

    def answer(self, request: VLMRequest) -> VLMResponse:
        raise PluginError(
            "openai_compatible_local backend is registered for discovery, but "
            "plugin-mode routing is reserved for a later phase. Stage 10 currently "
            "invokes call_openai_compatible_local directly via "
            "pipeline.stage_10_copilot.vlm_answer."
        )


class _PrecomputedDepthProvider:
    """Adapter for the Stage 6 ``provider="precomputed"`` mode.

    In precomputed mode Stage 6 expects the operator to drop ``*.npy``
    (or ``.npz``, ``.png``, ``.tif``, ``.tiff``, ``.pfm``) files into the
    configured ``da3.depth_input_dir``. The provider has nothing to compute;
    its job is to confirm that a depth file for each image exists. This
    adapter performs that check via the existing
    :func:`pipeline.stage_06_da3_assist.depth_provider.find_depth_maps`.
    """

    name = "precomputed"
    description = "Use externally-precomputed monocular depth maps from disk."

    def materialize(self, request: DepthProviderRequest) -> DepthProviderResult:
        from pipeline.stage_06_da3_assist.depth_provider import find_depth_maps  # noqa: WPS433

        extensions = list(request.options.get("extensions") or [".npy", ".npz", ".png", ".tif", ".tiff", ".pfm"])
        records = find_depth_maps(
            request.image_dir,
            request.output_dir,
            extensions=extensions,
            max_images=request.options.get("max_images"),
        )
        return DepthProviderResult(
            status="ok" if records else "not_configured",
            provider=self.name,
            image_count=len(records),
            notes=[] if records else [f"No precomputed depth maps found under {request.output_dir}"],
        )


class _ExternalCommandDepthProvider:
    """Adapter for the Stage 6 ``provider="external_command"`` mode."""

    name = "external_command"
    description = "Shell out to an external command that writes depth files into the output directory."

    def materialize(self, request: DepthProviderRequest) -> DepthProviderResult:
        raise PluginError(
            "external_command depth provider is registered for discovery, but "
            "plugin-mode routing is reserved for a later phase. Stage 6 currently "
            "invokes run_external_depth_provider directly via "
            "pipeline.stage_06_da3_assist.run_da3_assist."
        )


def build_default_plugin_registries() -> tuple[PluginRegistry[VLMBackend], PluginRegistry[DepthProvider]]:
    """Construct the canonical VLM and depth registries.

    Returned as a tuple so a caller (or a test) can build a fresh pair
    independently of the module-level singletons.
    """
    vlm: PluginRegistry[VLMBackend] = PluginRegistry(VLMBackend, "vlm_backend")
    vlm.register(PluginInfo(
        name="mock",
        description="Deterministic mock; no network. Always available.",
        factory=lambda: _MockVLMBackend(),
        capabilities=frozenset({"offline", "deterministic"}),
    ))
    vlm.register(PluginInfo(
        name="ollama_local",
        description="Local Ollama VLM (qwen3-vl etc.) over a private endpoint.",
        factory=lambda: _OllamaLocalVLMBackend(),
        capabilities=frozenset({"local_only", "requires_endpoint"}),
    ))
    vlm.register(PluginInfo(
        name="openai_compatible_local",
        description="Local OpenAI-compatible multimodal server (vLLM, LM Studio).",
        factory=lambda: _OpenAICompatibleLocalVLMBackend(),
        capabilities=frozenset({"local_only", "requires_endpoint"}),
    ))

    depth: PluginRegistry[DepthProvider] = PluginRegistry(DepthProvider, "depth_provider")
    depth.register(PluginInfo(
        name="precomputed",
        description="Use externally-precomputed depth maps from disk.",
        factory=lambda: _PrecomputedDepthProvider(),
        capabilities=frozenset({"offline"}),
    ))
    depth.register(PluginInfo(
        name="external_command",
        description="Shell out to an external command to materialize depth.",
        factory=lambda: _ExternalCommandDepthProvider(),
        capabilities=frozenset({"requires_external_binary"}),
    ))
    return vlm, depth


VLM_REGISTRY: PluginRegistry[VLMBackend]
DEPTH_REGISTRY: PluginRegistry[DepthProvider]
VLM_REGISTRY, DEPTH_REGISTRY = build_default_plugin_registries()
